Repository goravel/goravel, pull requests merged in 2023-06, with the labels that each got.

#147 Feat: [#49] Support Package Development
  config/app.go
  packages/sms/README.md
  packages/sms/config/sms.go
  packages/sms/contracts/sms.go
  packages/sms/facades/sms.go
  packages/sms/service_provider.go
  packages/sms/sms.go
Labels: Review Ready

#149 chore: delete .github folder
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/workflows/issue-auto-reply.yml
  .github/workflows/issue-close-question.yml
  .github/workflows/welcome.yml
Labels: Review Ready

#155 Revert "chore: delete .github folder"
  .github/workflows/issue-auto-reply.yml
  .github/workflows/issue-close-question.yml
  .github/workflows/welcome.yml
Labels: ☢️ Bug

#180 fix: CI auto reply
  .github/workflows/issue-auto-reply.yml
Labels: 🚀 Review Ready

#202 feat: optimize README and workflow
  .github/workflows/pr-check-title.yml
  README.md
  README_zh.md
Labels: 🚀 Review Ready
